version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp # collect zipkin.thrift via compact thrift
      - 6831:6831/udp # collect jaeger.thrift via compact thrift
      - 6832:6832/udp # collect jaeger.thrift via binary thrift
      - 5778:5778 # configs
      - 16686:16686 # frontend
      - 14268:14268 # collect jaeger.thrift directly from clients

  http-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
